[2025-10-24T10:57:17.559+0000] {processor.py:186} INFO - Started process (PID=1338) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T10:57:17.560+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T10:57:17.563+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:57:17.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T10:57:17.628+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:57:17.619+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T10:57:17.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T10:57:17.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.097 seconds
[2025-10-24T10:57:47.822+0000] {processor.py:186} INFO - Started process (PID=1403) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T10:57:47.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T10:57:47.826+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:57:47.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T10:57:47.868+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:57:47.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T10:57:47.871+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T10:57:47.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.104 seconds
[2025-10-24T10:58:18.278+0000] {processor.py:186} INFO - Started process (PID=1474) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T10:58:18.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T10:58:18.283+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:58:18.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T10:58:18.315+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:58:18.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T10:58:18.316+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T10:58:18.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.061 seconds
[2025-10-24T10:58:49.139+0000] {processor.py:186} INFO - Started process (PID=1539) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T10:58:49.141+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T10:58:49.144+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:58:49.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T10:58:49.208+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:58:49.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T10:58:49.213+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T10:58:49.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.133 seconds
[2025-10-24T10:59:19.952+0000] {processor.py:186} INFO - Started process (PID=1604) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T10:59:19.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T10:59:19.955+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:59:19.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T10:59:19.979+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:59:19.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T10:59:19.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T10:59:19.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.053 seconds
[2025-10-24T10:59:50.383+0000] {processor.py:186} INFO - Started process (PID=1669) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T10:59:50.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T10:59:50.388+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:59:50.387+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T10:59:50.410+0000] {logging_mixin.py:190} INFO - [2025-10-24T10:59:50.406+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T10:59:50.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T10:59:50.431+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.055 seconds
[2025-10-24T11:00:20.619+0000] {processor.py:186} INFO - Started process (PID=1734) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:00:20.620+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:00:20.623+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:00:20.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:00:20.641+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:00:20.638+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:00:20.642+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:00:20.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.042 seconds
[2025-10-24T11:00:50.961+0000] {processor.py:186} INFO - Started process (PID=1798) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:00:50.963+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:00:50.966+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:00:50.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:00:50.995+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:00:50.988+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:00:50.997+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:00:51.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.060 seconds
[2025-10-24T11:01:16.773+0000] {processor.py:186} INFO - Started process (PID=1829) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:01:16.775+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:01:16.777+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:01:16.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:01:16.827+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:01:16.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:01:16.829+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:01:16.848+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.079 seconds
[2025-10-24T11:01:46.964+0000] {processor.py:186} INFO - Started process (PID=1894) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:01:46.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:01:46.967+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:01:46.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:01:46.987+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:01:46.982+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:01:46.988+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:01:47.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.044 seconds
[2025-10-24T11:02:17.129+0000] {processor.py:186} INFO - Started process (PID=1959) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:02:17.130+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:02:17.133+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:02:17.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:02:17.147+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:02:17.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:02:17.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:02:17.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.038 seconds
[2025-10-24T11:02:47.257+0000] {processor.py:186} INFO - Started process (PID=2024) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:02:47.258+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:02:47.260+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:02:47.260+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:02:47.281+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:02:47.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:02:47.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:02:47.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.043 seconds
[2025-10-24T11:03:18.078+0000] {processor.py:186} INFO - Started process (PID=2095) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:18.080+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:03:18.082+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:03:18.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:18.111+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:03:18.106+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:03:18.113+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:18.131+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.057 seconds
[2025-10-24T11:03:48.767+0000] {processor.py:186} INFO - Started process (PID=2160) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:48.768+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:03:48.770+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:03:48.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:48.785+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:03:48.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:03:48.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:48.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.037 seconds
[2025-10-24T11:03:58.306+0000] {processor.py:186} INFO - Started process (PID=2190) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:58.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:03:58.309+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:03:58.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:58.342+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:03:58.338+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:03:58.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:03:58.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.058 seconds
[2025-10-24T11:04:28.835+0000] {processor.py:186} INFO - Started process (PID=2255) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:04:28.836+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:04:28.839+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:04:28.838+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:04:28.869+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:04:28.863+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:04:28.872+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:04:28.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.056 seconds
[2025-10-24T11:04:43.077+0000] {processor.py:186} INFO - Started process (PID=2280) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:04:43.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:04:43.080+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:04:43.080+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:04:43.110+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:04:43.107+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:04:43.111+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:04:43.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.054 seconds
[2025-10-24T11:05:13.467+0000] {processor.py:186} INFO - Started process (PID=2345) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:05:13.468+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:05:13.470+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:05:13.470+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:05:13.508+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:05:13.503+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:05:13.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:05:13.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.063 seconds
[2025-10-24T11:05:44.009+0000] {processor.py:186} INFO - Started process (PID=2410) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:05:44.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:05:44.011+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:05:44.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:05:44.027+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:05:44.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:05:44.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:05:44.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.038 seconds
[2025-10-24T11:06:14.856+0000] {processor.py:186} INFO - Started process (PID=2475) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:06:14.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:06:14.859+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:06:14.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:06:14.875+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:06:14.873+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:06:14.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:06:14.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.038 seconds
[2025-10-24T11:06:45.569+0000] {processor.py:186} INFO - Started process (PID=2540) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:06:45.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:06:45.572+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:06:45.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:06:45.589+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:06:45.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:06:45.590+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:06:45.613+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.048 seconds
[2025-10-24T11:07:07.305+0000] {processor.py:186} INFO - Started process (PID=2581) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:07:07.307+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:07:07.309+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:07:07.309+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:07:07.336+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:07:07.333+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:07:07.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:07:07.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.057 seconds
[2025-10-24T11:07:38.197+0000] {processor.py:186} INFO - Started process (PID=2646) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:07:38.198+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:07:38.200+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:07:38.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:07:38.215+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:07:38.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:07:38.217+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:07:38.232+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.039 seconds
[2025-10-24T11:08:08.262+0000] {processor.py:186} INFO - Started process (PID=2711) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:08:08.264+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:08:08.266+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:08:08.265+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:08:08.280+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:08:08.277+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:08:08.284+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:08:08.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.044 seconds
[2025-10-24T11:08:39.304+0000] {processor.py:186} INFO - Started process (PID=2776) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:08:39.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:08:39.317+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:08:39.316+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:08:39.351+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:08:39.345+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:08:39.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:08:39.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.102 seconds
[2025-10-24T11:09:12.276+0000] {processor.py:186} INFO - Started process (PID=59) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:09:12.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:09:12.279+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:09:12.279+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:09:12.319+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:09:12.311+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:09:12.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:09:12.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.069 seconds
[2025-10-24T11:09:42.474+0000] {processor.py:186} INFO - Started process (PID=124) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:09:42.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:09:42.480+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:09:42.480+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:09:42.492+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:09:42.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:09:42.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:09:42.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.045 seconds
[2025-10-24T11:10:12.929+0000] {processor.py:186} INFO - Started process (PID=189) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:10:12.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:10:12.933+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:10:12.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:10:12.951+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:10:12.947+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:10:12.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:10:12.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.047 seconds
[2025-10-24T11:10:43.088+0000] {processor.py:186} INFO - Started process (PID=254) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:10:43.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:10:43.091+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:10:43.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:10:43.128+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:10:43.121+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:10:43.130+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:10:43.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.065 seconds
[2025-10-24T11:11:13.542+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:11:13.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:11:13.545+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:11:13.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:11:13.560+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:11:13.555+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:11:13.561+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:11:13.575+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.037 seconds
[2025-10-24T11:11:43.870+0000] {processor.py:186} INFO - Started process (PID=384) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:11:43.871+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:11:43.874+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:11:43.874+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:11:43.906+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:11:43.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:11:43.910+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:11:43.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.062 seconds
[2025-10-24T11:12:14.202+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:12:14.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:12:14.205+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:12:14.205+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:12:14.218+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:12:14.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:12:14.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:12:14.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.038 seconds
[2025-10-24T11:12:44.344+0000] {processor.py:186} INFO - Started process (PID=514) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:12:44.345+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:12:44.347+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:12:44.347+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:12:44.366+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:12:44.364+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:12:44.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:12:44.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.045 seconds
[2025-10-24T11:13:15.034+0000] {processor.py:186} INFO - Started process (PID=579) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:13:15.035+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:13:15.038+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:13:15.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:13:15.054+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:13:15.050+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:13:15.055+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:13:15.071+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.042 seconds
[2025-10-24T11:13:45.178+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:13:45.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:13:45.184+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:13:45.184+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:13:45.200+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:13:45.197+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:13:45.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:13:45.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.043 seconds
[2025-10-24T11:14:15.627+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:14:15.630+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:14:15.633+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:14:15.632+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:14:15.662+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:14:15.657+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 3, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'
[2025-10-24T11:14:15.664+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:14:15.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.057 seconds
[2025-10-24T11:14:46.107+0000] {processor.py:186} INFO - Started process (PID=799) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:14:46.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:14:46.119+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:14:46.119+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:14:46.174+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:14:46.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:14:46.175+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:14:46.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.089 seconds
[2025-10-24T11:15:17.022+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:15:17.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:15:17.025+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:15:17.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:15:17.078+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:15:17.072+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:15:17.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:15:17.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.078 seconds
[2025-10-24T11:15:47.198+0000] {processor.py:186} INFO - Started process (PID=935) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:15:47.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:15:47.201+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:15:47.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:15:47.252+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:15:47.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:15:47.254+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:15:47.266+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.074 seconds
[2025-10-24T11:16:18.223+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:16:18.224+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:16:18.226+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:16:18.226+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:16:18.281+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:16:18.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:16:18.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:16:18.297+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.083 seconds
[2025-10-24T11:16:49.282+0000] {processor.py:186} INFO - Started process (PID=1065) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:16:49.283+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:16:49.285+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:16:49.285+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:16:49.338+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:16:49.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:16:49.339+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:16:49.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.078 seconds
[2025-10-24T11:17:19.496+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:17:19.497+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:17:19.498+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:17:19.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:17:19.551+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:17:19.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:17:19.552+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:17:19.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.077 seconds
[2025-10-24T11:17:50.072+0000] {processor.py:186} INFO - Started process (PID=1194) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:17:50.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:17:50.076+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:17:50.076+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:17:50.145+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:17:50.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:17:50.147+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:17:50.162+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.096 seconds
[2025-10-24T11:18:20.936+0000] {processor.py:186} INFO - Started process (PID=1259) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:18:20.942+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:18:20.944+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:18:20.944+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:18:20.999+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:18:20.993+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:18:21.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:18:21.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.083 seconds
[2025-10-24T11:18:51.438+0000] {processor.py:186} INFO - Started process (PID=1324) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:18:51.439+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:18:51.441+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:18:51.441+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:18:51.500+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:18:51.493+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:18:51.502+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:18:51.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.082 seconds
[2025-10-24T11:19:21.832+0000] {processor.py:186} INFO - Started process (PID=1389) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:19:21.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:19:21.837+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:19:21.836+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:19:21.926+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:19:21.915+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:19:21.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:19:21.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.122 seconds
[2025-10-24T11:19:52.772+0000] {processor.py:186} INFO - Started process (PID=1454) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:19:52.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:19:52.776+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:19:52.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:19:52.703+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:19:52.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:19:52.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:19:52.720+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.088 seconds
[2025-10-24T11:20:23.329+0000] {processor.py:186} INFO - Started process (PID=1519) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:20:23.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:20:23.336+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:20:23.336+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:20:23.504+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:20:23.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:20:23.507+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:20:23.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.198 seconds
[2025-10-24T11:20:54.491+0000] {processor.py:186} INFO - Started process (PID=1584) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:20:54.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:20:54.495+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:20:54.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:20:54.547+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:20:54.542+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:20:54.548+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:20:54.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.075 seconds
[2025-10-24T11:21:24.645+0000] {processor.py:186} INFO - Started process (PID=1650) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:21:24.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:21:24.648+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:21:24.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:21:24.701+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:21:24.696+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:21:24.703+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:21:24.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.075 seconds
[2025-10-24T11:21:55.582+0000] {processor.py:186} INFO - Started process (PID=1714) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:21:55.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:21:55.586+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:21:55.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:21:55.656+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:21:55.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:21:55.659+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:21:55.674+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.097 seconds
[2025-10-24T11:22:26.714+0000] {processor.py:186} INFO - Started process (PID=1779) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:22:26.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:22:26.720+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:22:26.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:22:26.890+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:22:26.879+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:22:26.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:22:26.907+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.204 seconds
[2025-10-24T11:22:57.154+0000] {processor.py:186} INFO - Started process (PID=1844) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:22:57.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:22:57.163+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:22:57.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:22:57.227+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:22:57.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:22:57.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:22:57.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.099 seconds
[2025-10-24T11:23:27.534+0000] {processor.py:186} INFO - Started process (PID=1909) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:23:27.538+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:23:27.541+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:23:27.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:23:27.634+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:23:27.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:23:27.636+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:23:27.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.124 seconds
[2025-10-24T11:23:57.835+0000] {processor.py:186} INFO - Started process (PID=1974) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:23:57.837+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:23:57.839+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:23:57.839+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:23:57.920+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:23:57.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:23:57.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:23:57.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.112 seconds
[2025-10-24T11:24:28.848+0000] {processor.py:186} INFO - Started process (PID=2039) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:24:28.849+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:24:28.851+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:24:28.851+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:24:28.918+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:24:28.910+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:24:28.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:24:28.936+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.093 seconds
[2025-10-24T11:24:59.578+0000] {processor.py:186} INFO - Started process (PID=2104) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:24:59.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:24:59.581+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:24:59.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:24:59.631+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:24:59.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:24:59.632+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:24:59.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.090 seconds
[2025-10-24T11:25:29.710+0000] {processor.py:186} INFO - Started process (PID=2169) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:25:29.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:25:29.713+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:25:29.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:25:29.763+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:25:29.757+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:25:29.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:25:29.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.079 seconds
[2025-10-24T11:26:00.090+0000] {processor.py:186} INFO - Started process (PID=2234) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:26:00.092+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:26:00.095+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:26:00.095+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:26:00.173+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:26:00.159+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:26:00.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:26:00.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.106 seconds
[2025-10-24T11:26:30.744+0000] {processor.py:186} INFO - Started process (PID=2299) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:26:30.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:26:30.748+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:26:30.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:26:30.824+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:26:30.817+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:26:30.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:26:30.841+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.105 seconds
[2025-10-24T11:27:01.347+0000] {processor.py:186} INFO - Started process (PID=2364) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:27:01.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:27:01.354+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:27:01.354+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:27:01.493+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:27:01.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:27:01.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:27:01.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.170 seconds
[2025-10-24T11:27:31.635+0000] {processor.py:186} INFO - Started process (PID=2429) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:27:31.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:27:31.638+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:27:31.638+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:27:31.687+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:27:31.683+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:27:31.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:27:31.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.072 seconds
[2025-10-24T11:28:02.314+0000] {processor.py:186} INFO - Started process (PID=2494) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:28:02.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:28:02.320+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:28:02.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:28:02.538+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:28:02.517+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:28:02.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:28:02.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.259 seconds
[2025-10-24T11:28:32.928+0000] {processor.py:186} INFO - Started process (PID=2559) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:28:32.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:28:32.932+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:28:32.931+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:28:32.997+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:28:32.991+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:28:32.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:28:33.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.091 seconds
[2025-10-24T11:29:03.081+0000] {processor.py:186} INFO - Started process (PID=2624) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:29:03.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:29:03.084+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:29:03.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:29:03.142+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:29:03.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:29:03.144+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:29:03.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.082 seconds
[2025-10-24T11:29:33.745+0000] {processor.py:186} INFO - Started process (PID=2689) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:29:33.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:29:33.751+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:29:33.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:29:33.823+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:29:33.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:29:33.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:29:33.843+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.104 seconds
[2025-10-24T11:30:04.629+0000] {processor.py:186} INFO - Started process (PID=2754) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:30:04.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:30:04.633+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:30:04.633+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:30:04.695+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:30:04.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:30:04.696+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:30:04.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.089 seconds
[2025-10-24T11:30:34.973+0000] {processor.py:186} INFO - Started process (PID=2819) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:30:34.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:30:34.976+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:30:34.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:30:35.043+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:30:35.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:30:35.046+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:30:35.061+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.095 seconds
[2025-10-24T11:31:06.043+0000] {processor.py:186} INFO - Started process (PID=2885) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:31:06.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:31:06.046+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:31:06.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:31:06.101+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:31:06.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:31:06.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:31:06.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.081 seconds
[2025-10-24T11:31:36.864+0000] {processor.py:186} INFO - Started process (PID=2950) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:31:36.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:31:36.867+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:31:36.867+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:31:36.920+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:31:36.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:31:36.921+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:31:36.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.079 seconds
[2025-10-24T11:32:07.342+0000] {processor.py:186} INFO - Started process (PID=3015) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:32:07.343+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:32:07.345+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:32:07.345+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:32:07.405+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:32:07.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:32:07.407+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:32:07.423+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.087 seconds
[2025-10-24T11:32:37.926+0000] {processor.py:186} INFO - Started process (PID=3080) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:32:37.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:32:37.929+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:32:37.929+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:32:37.978+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:32:37.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:32:37.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:32:37.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.078 seconds
[2025-10-24T11:33:08.058+0000] {processor.py:186} INFO - Started process (PID=3145) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:33:08.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:33:08.067+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:33:08.067+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:33:08.124+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:33:08.117+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:33:08.126+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:33:08.140+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.089 seconds
[2025-10-24T11:33:38.492+0000] {processor.py:186} INFO - Started process (PID=3210) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:33:38.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:33:38.495+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:33:38.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:33:38.564+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:33:38.556+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:33:38.565+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:33:38.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.096 seconds
[2025-10-24T11:34:08.747+0000] {processor.py:186} INFO - Started process (PID=3275) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:34:08.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:34:08.750+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:34:08.750+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:34:08.811+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:34:08.802+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:34:08.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:34:08.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.087 seconds
[2025-10-24T11:34:39.675+0000] {processor.py:186} INFO - Started process (PID=3340) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:34:39.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:34:39.678+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:34:39.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:34:39.727+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:34:39.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:34:39.730+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:34:39.753+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.084 seconds
[2025-10-24T11:35:10.089+0000] {processor.py:186} INFO - Started process (PID=3405) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:35:10.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:35:10.092+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:35:10.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:35:10.144+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:35:10.141+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:35:10.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:35:10.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.075 seconds
[2025-10-24T11:35:40.685+0000] {processor.py:186} INFO - Started process (PID=3459) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:35:40.685+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:35:40.687+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:35:40.687+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:35:40.733+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:35:40.730+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:35:40.734+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:35:40.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.069 seconds
[2025-10-24T11:36:11.629+0000] {processor.py:186} INFO - Started process (PID=3516) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:36:11.629+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:36:11.631+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:36:11.631+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:36:11.679+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:36:11.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:36:11.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:36:11.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.072 seconds
[2025-10-24T11:36:42.768+0000] {processor.py:186} INFO - Started process (PID=3579) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:36:42.771+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:36:42.775+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:36:42.774+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:36:42.861+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:36:42.849+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:36:42.864+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:36:42.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.122 seconds
[2025-10-24T11:37:13.841+0000] {processor.py:186} INFO - Started process (PID=3644) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:37:13.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:37:13.844+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:37:13.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:37:13.912+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:37:13.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:37:13.914+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:37:13.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.093 seconds
[2025-10-24T11:37:44.865+0000] {processor.py:186} INFO - Started process (PID=3709) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:37:44.866+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:37:44.869+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:37:44.868+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:37:44.976+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:37:44.936+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:37:44.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:37:45.000+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.142 seconds
[2025-10-24T11:38:15.516+0000] {processor.py:186} INFO - Started process (PID=3780) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:38:15.517+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:38:15.518+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:38:15.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:38:15.565+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:38:15.562+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:38:15.566+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:38:15.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.069 seconds
[2025-10-24T11:38:45.931+0000] {processor.py:186} INFO - Started process (PID=3842) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:38:45.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:38:45.935+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:38:45.934+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:38:46.004+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:38:45.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:38:46.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:38:46.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.095 seconds
[2025-10-24T11:39:16.278+0000] {processor.py:186} INFO - Started process (PID=3902) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:39:16.280+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:39:16.282+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:39:16.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:39:16.376+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:39:16.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:39:16.380+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:39:16.401+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.130 seconds
[2025-10-24T11:39:46.792+0000] {processor.py:186} INFO - Started process (PID=3966) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:39:46.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:39:46.796+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:39:46.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:39:46.874+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:39:46.871+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:39:46.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:39:46.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.103 seconds
[2025-10-24T11:40:17.382+0000] {processor.py:186} INFO - Started process (PID=4019) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:40:17.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:40:17.387+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:40:17.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:40:17.463+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:40:17.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:40:17.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:40:17.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.105 seconds
[2025-10-24T11:40:47.633+0000] {processor.py:186} INFO - Started process (PID=4078) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:40:47.634+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:40:47.636+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:40:47.635+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:40:47.682+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:40:47.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:40:47.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:40:47.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.067 seconds
[2025-10-24T11:41:18.437+0000] {processor.py:186} INFO - Started process (PID=4143) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:41:18.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:41:18.439+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:41:18.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:41:18.488+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:41:18.483+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:41:18.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:41:18.504+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.074 seconds
[2025-10-24T11:41:49.179+0000] {processor.py:186} INFO - Started process (PID=4208) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:41:49.180+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:41:49.182+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:41:49.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:41:49.228+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:41:49.225+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:41:49.230+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:41:49.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.068 seconds
[2025-10-24T11:42:19.675+0000] {processor.py:186} INFO - Started process (PID=4270) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:42:19.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:42:19.678+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:42:19.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:42:19.726+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:42:19.723+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:42:19.727+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:42:19.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.070 seconds
[2025-10-24T11:42:50.247+0000] {processor.py:186} INFO - Started process (PID=4334) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:42:50.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:42:50.250+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:42:50.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:42:50.298+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:42:50.296+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:42:50.299+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:42:50.312+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.071 seconds
[2025-10-24T11:43:20.710+0000] {processor.py:186} INFO - Started process (PID=4396) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:43:20.711+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:43:20.713+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:43:20.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:43:20.768+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:43:20.762+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:43:20.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:43:20.786+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.081 seconds
[2025-10-24T11:43:51.216+0000] {processor.py:186} INFO - Started process (PID=4461) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:43:51.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:43:51.220+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:43:51.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:43:51.429+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:43:51.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:43:51.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:43:51.441+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.231 seconds
[2025-10-24T11:44:21.808+0000] {processor.py:186} INFO - Started process (PID=4526) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:44:21.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:44:21.811+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:44:21.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:44:22.006+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:44:22.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:44:22.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:44:22.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.216 seconds
[2025-10-24T11:44:52.315+0000] {processor.py:186} INFO - Started process (PID=4592) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:44:52.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:44:52.318+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:44:52.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:44:52.574+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:44:52.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:44:52.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:44:52.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.281 seconds
[2025-10-24T11:45:22.879+0000] {processor.py:186} INFO - Started process (PID=4657) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:45:22.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:45:22.882+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:45:22.882+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:45:23.076+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:45:23.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:45:23.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:45:23.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.216 seconds
[2025-10-24T11:45:53.165+0000] {processor.py:186} INFO - Started process (PID=4721) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:45:53.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:45:53.168+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:45:53.168+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:45:53.352+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:45:53.350+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:45:53.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:45:53.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.205 seconds
[2025-10-24T11:46:23.673+0000] {processor.py:186} INFO - Started process (PID=4788) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:46:23.674+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:46:23.676+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:46:23.676+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:46:23.863+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:46:23.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:46:23.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:46:23.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.213 seconds
[2025-10-24T11:46:54.126+0000] {processor.py:186} INFO - Started process (PID=4851) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:46:54.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:46:54.129+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:46:54.129+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:46:54.336+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:46:54.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:46:54.338+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:46:54.350+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.230 seconds
[2025-10-24T11:47:25.363+0000] {processor.py:186} INFO - Started process (PID=4915) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:47:25.364+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:47:25.369+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:47:25.369+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:47:25.563+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:47:25.561+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:47:25.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:47:25.580+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.223 seconds
[2025-10-24T11:47:55.984+0000] {processor.py:186} INFO - Started process (PID=4979) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:47:55.985+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:47:55.987+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:47:55.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:47:56.156+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:47:56.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:47:56.158+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:47:56.169+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.191 seconds
[2025-10-24T11:48:26.387+0000] {processor.py:186} INFO - Started process (PID=5045) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:48:26.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:48:26.390+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:48:26.390+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:48:26.590+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:48:26.583+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:48:26.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:48:26.606+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.225 seconds
[2025-10-24T11:48:57.378+0000] {processor.py:186} INFO - Started process (PID=5110) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:48:57.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:48:57.384+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:48:57.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:48:57.580+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:48:57.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:48:57.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:48:57.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.222 seconds
[2025-10-24T11:49:28.088+0000] {processor.py:186} INFO - Started process (PID=5174) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:49:28.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:49:28.091+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:49:28.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:49:28.144+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:49:28.137+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:49:28.145+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:49:28.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.076 seconds
[2025-10-24T11:49:58.986+0000] {processor.py:186} INFO - Started process (PID=5239) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:49:58.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:49:58.991+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:49:58.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:49:59.047+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:49:59.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:49:59.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:49:59.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.083 seconds
[2025-10-24T11:50:29.450+0000] {processor.py:186} INFO - Started process (PID=5304) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:50:29.451+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:50:29.453+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:50:29.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:50:29.510+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:50:29.505+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:50:29.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:50:29.528+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.083 seconds
[2025-10-24T11:50:59.914+0000] {processor.py:186} INFO - Started process (PID=5369) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:50:59.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:50:59.919+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:50:59.919+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:50:59.973+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:50:59.965+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:50:59.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:50:59.989+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.081 seconds
[2025-10-24T11:51:30.391+0000] {processor.py:186} INFO - Started process (PID=5434) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:51:30.391+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:51:30.393+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:51:30.393+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:51:30.449+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:51:30.444+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:51:30.450+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:51:30.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.079 seconds
[2025-10-24T11:52:00.869+0000] {processor.py:186} INFO - Started process (PID=5499) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:52:00.870+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:52:00.872+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:52:00.872+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:52:00.925+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:52:00.920+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:52:00.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:52:00.939+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.077 seconds
[2025-10-24T11:52:31.324+0000] {processor.py:186} INFO - Started process (PID=5564) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:52:31.325+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:52:31.327+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:52:31.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:52:31.389+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:52:31.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:52:31.390+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:52:31.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.085 seconds
[2025-10-24T11:53:01.799+0000] {processor.py:186} INFO - Started process (PID=5629) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:53:01.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:53:01.809+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:53:01.808+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:53:01.875+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:53:01.870+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:53:01.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:53:01.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.096 seconds
[2025-10-24T11:53:32.295+0000] {processor.py:186} INFO - Started process (PID=5695) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:53:32.296+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:53:32.298+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:53:32.298+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:53:32.373+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:53:32.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:53:32.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:53:32.388+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.099 seconds
[2025-10-24T11:54:03.050+0000] {processor.py:186} INFO - Started process (PID=5760) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:54:03.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:54:03.057+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:54:03.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:54:03.128+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:54:03.122+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:54:03.131+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:54:03.146+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.101 seconds
[2025-10-24T11:54:33.550+0000] {processor.py:186} INFO - Started process (PID=5825) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:54:33.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:54:33.555+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:54:33.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:54:33.626+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:54:33.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:54:33.631+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:54:33.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.101 seconds
[2025-10-24T11:55:04.190+0000] {processor.py:186} INFO - Started process (PID=5890) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:55:04.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:55:04.194+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:55:04.193+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:55:04.256+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:55:04.249+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:55:04.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:55:04.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.087 seconds
[2025-10-24T11:55:34.597+0000] {processor.py:186} INFO - Started process (PID=5956) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:55:34.598+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:55:34.600+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:55:34.600+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:55:34.651+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:55:34.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:55:34.652+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:55:34.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.073 seconds
[2025-10-24T11:56:05.240+0000] {processor.py:186} INFO - Started process (PID=6021) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:56:05.243+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:56:05.247+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:56:05.247+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:56:05.353+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:56:05.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:56:05.362+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:56:05.379+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.145 seconds
[2025-10-24T11:56:35.804+0000] {processor.py:186} INFO - Started process (PID=6086) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:56:35.805+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:56:35.807+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:56:35.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:56:35.861+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:56:35.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:56:35.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:56:35.880+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.082 seconds
[2025-10-24T11:57:06.298+0000] {processor.py:186} INFO - Started process (PID=6151) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:57:06.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:57:06.302+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:57:06.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:57:06.377+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:57:06.368+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:57:06.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:57:06.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.101 seconds
[2025-10-24T11:57:37.289+0000] {processor.py:186} INFO - Started process (PID=6216) to work on /opt/airflow/dags/DEPI.py
[2025-10-24T11:57:37.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/DEPI.py for tasks to queue
[2025-10-24T11:57:37.292+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:57:37.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/DEPI.py
[2025-10-24T11:57:37.343+0000] {logging_mixin.py:190} INFO - [2025-10-24T11:57:37.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/DEPI.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/DEPI.py", line 5, in <module>
    from airflow.providers.standard.operators.python import PythonOperator
ModuleNotFoundError: No module named 'airflow.providers.standard'
[2025-10-24T11:57:37.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/DEPI.py
[2025-10-24T11:57:37.357+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/DEPI.py took 0.073 seconds
